Kleine Erweiterungen
PolylymerDE/NoRiskClientBotRemastered pull request #13
Opened 2021-06-01 15:45 UTC by MatrixCodeDE

Blacklist Listener angepasst
Template Command

2021-06-01 15:50 UTC, mooziii requested changes

2021-06-01 15:50 UTC, mooziii commented on src/main/kotlin/de/polylymer/commands/implementation/TemplateCommand.kt
> +            content = "Achtung: Der Capeserver ist im Moment nicht erreichbar!"
This won't work. You have to put it in the next line with `\n`

2021-06-01 16:15 UTC, MatrixCodeDE commented on src/main/kotlin/de/polylymer/commands/implementation/TemplateCommand.kt
> +            content = "Achtung: Der Capeserver ist im Moment nicht erreichbar!"
Gefixt und du kannst Deutsch schreiben :)

2021-06-01 16:17 UTC, MatrixCodeDE commented on src/main/kotlin/de/polylymer/commands/implementation/BlacklistCommand.kt
> +            if (!this.member!!.isBot || this.member!!.memberData.roles.isEmpty) {
Ist nur für die Reaktion auf Offline etc gedacht, da Leute mit Rollen das schließlich wissen

2021-06-01 16:20 UTC, MatrixCodeDE commented on src/main/kotlin/de/polylymer/commands/implementation/BlacklistCommand.kt
> +            if (!this.member!!.isBot || this.member!!.memberData.roles.isEmpty()) {
Ist nur für Listener auf Offline etc gedacht, da Leute mit Rollen das bereits wissen sollten

2021-06-01 16:21 UTC, mooziii requested changes

2021-06-01 16:21 UTC, mooziii commented on src/main/kotlin/de/polylymer/commands/implementation/SurvivalCommand.kt
> +    var list = listOf("Test", "Test2", "Test3")
???

2021-06-01 16:37 UTC, MatrixCodeDE commented on src/main/kotlin/de/polylymer/commands/implementation/SurvivalCommand.kt
> +    var list = listOf("Test", "Test2", "Test3")
Anfrage von Taito für nen neuen Befehl

2021-06-01 16:39 UTC, mooziii commented on src/main/kotlin/de/polylymer/commands/implementation/SurvivalCommand.kt
> +    var list = listOf("Test", "Test2", "Test3")
ja aber in der liste iost ja nur "test"

2021-06-01 20:52 UTC, MatrixCodeDE commented on src/main/kotlin/de/polylymer/commands/implementation/SurvivalCommand.kt
> +    var list = listOf("Test", "Test2", "Test3")
Man kann die ja noch befüllen :/

2021-06-01 20:56 UTC, polylymer commented on src/main/kotlin/de/polylymer/commands/implementation/SurvivalCommand.kt
> +    var list = listOf("Test", "Test2", "Test3")
lol dann befüll sie doch oder kommentier es aus

2021-06-01 21:32 UTC, MatrixCodeDE commented on src/main/kotlin/de/polylymer/commands/implementation/SurvivalCommand.kt
> +    var list = listOf("Test", "Test2", "Test3")
Jo is gemacht

2021-06-02 11:37 UTC, mooziii requested changes
ich werd blöd

mach doch ein /roles command bei dem ein embed mit allen roles kommt

2021-06-02 11:38 UTC, mooziii requested changes

2021-06-02 11:38 UTC, mooziii commented on src/main/kotlin/de/polylymer/commands/implementation/SurvivalCommand.kt
> +    //var list = listOf("Test", "Test2", "Test3")
das würde ein fehler verursachen da das objekt "list" nicht existiert

2021-06-02 11:38 UTC, mooziii commented on src/main/kotlin/de/polylymer/commands/implementation/SurvivalCommand.kt
>          interaction.ackowledgePublic().followUp {
warum schickst du hier sachen aus der liste von /random?

2021-06-02 11:59 UTC, mooziii requested changes
keiner dieser commands ist registriert

2021-06-02 12:00 UTC, mooziii commented
egal will dich nicht nerven mach das mit roles anders dann merge ich und ich mach den rest

2021-06-02 16:43 UTC, MatrixCodeDE commented on src/main/kotlin/de/polylymer/commands/implementation/SurvivalCommand.kt
>          interaction.ackowledgePublic().followUp {
wunsch von taito immernoch -_-

2021-06-02 16:54 UTC, mooziii commented on src/main/kotlin/de/polylymer/commands/implementation/SurvivalCommand.kt
>          interaction.ackowledgePublic().followUp {
ja junge du schickst aber aus der liste von /random und nicht von /survival

2021-06-02 20:39 UTC, MatrixCodeDE commented on src/main/kotlin/de/polylymer/listener/MessageListener.kt
> +                    if (this.message.content.toLowerCase().contains("omegalul")) {
Idee von Helpless

2021-06-02 20:46 UTC, mooziii requested changes

2021-06-02 20:46 UTC, mooziii commented on src/main/kotlin/de/polylymer/commands/implementation/SurvivalCommand.kt
> +            //content = RandomCommand.list.random().replace("{ping}", interaction.member().asMember().mention)
jetzt würde da ewig "NoRiskClienBot denkt nach..." stehen

2021-06-02 20:46 UTC, mooziii commented on src/main/kotlin/de/polylymer/listener/MessageListener.kt
> +                        this.message.reply { content = "Matrix will nicht gepingt werden, daher der Prefix..." }
was zum

2021-06-02 20:46 UTC, mooziii commented on src/main/kotlin/de/polylymer/listener/MessageListener.kt
> +                    if(this.message.content.contains("@[NoPing] MatrixGraphicz")) {
das würde nicht gehen du musst danach abfragen `<@!ID>`

2021-06-02 20:46 UTC, mooziii commented on src/main/kotlin/de/polylymer/listener/MessageListener.kt
> +                    if (this.message.content.toLowerCase().contains("omegalul")) {
ich frage einfach nicht

2021-06-02 20:53 UTC, merged