Update xD reaction
PolylymerDE/NoRiskClientBotRemastered pull request #5
Opened 2021-05-29 19:05 UTC by Indikativ

now everyone in that list __12YearOls_ gets reacted by the bot mit 12 even if they write it in lowercase or uppercase or anything
und ich bekomme keine reaction wenn ich sowas schreibe :DDDD
ist scheiße gecodet warscheinlich weil ich bin nix gut in kotlin bin
geht warscheinlich einfacher :disappointed:
wieso hab ich von main auf main ich weiß nicht was das bedeutet aber ich konnte in keine andere branch wegen error

2021-05-29 19:08 UTC, mooziii requested changes

2021-05-29 19:08 UTC, mooziii commented on src/main/kotlin/de/polylymer/listener/MessageListener.kt
> +                                        Thread.sleep(500)
Using `Thread#sleep` here will cause everything to stop for 0.5 seconds
Also it isn't usefull here

2021-05-29 19:08 UTC, mooziii requested changes

2021-05-29 19:08 UTC, mooziii commented on src/main/kotlin/de/polylymer/listener/MessageListener.kt
> +
Remove useless space

2021-05-29 19:08 UTC, mooziii commented on src/main/kotlin/de/polylymer/listener/MessageListener.kt
> +    val _12YearOlds = listOf("370219437242187788", "848254211263430726", "707116990652743721")
Put this into a config

2021-05-29 19:09 UTC, mooziii commented
Würde es eig auch bei nur `xD` belassen das ist sonst kranker abfuck wenn unter fast jeder Nachricht eine reaction ist

2021-05-29 19:46 UTC, Indikativ commented
eigentlich war es der sinn der pr dass man bei allen xd's 12 bekommt aber halt nur bei denen die in _12YearOls sind kannst ja adden und hinzufügen

2021-05-30 08:11 UTC, mooziii commented on src/main/kotlin/de/polylymer/listener/MessageListener.kt
> ->>>>>>> Stashed changes
ähm du hast halt einfach nur den merge conflict gepusht

2021-05-30 08:52 UTC, Indikativ commented on src/main/kotlin/de/polylymer/listener/MessageListener.kt
> ->>>>>>> Stashed changes
ehm kenne mich noch nid so gut mit github aus wait ich fix kurz

2021-05-30 08:55 UTC, Indikativ commented
frag nicht ok?

2021-05-30 08:56 UTC, Indikativ commented
hab noch geaddet dass wenn man hast du eig obsi schreibt man obsi oder ne bekommt vom bot (obsi 1 in 5 chance)

2021-05-30 08:58 UTC, mooziii requested changes
mach das `Thread.sleep(...)` noch raus dann gut

2021-05-30 10:55 UTC, mooziii approved these changes

2021-05-30 10:55 UTC, merged